name: tracekit_workspace
repository: https://github.com/tracekit/tracekit

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze --fatal-warnings
    description: Run dart analyze in all packages.
  test:
    run: melos exec -- dart test
    description: Run unit tests in all packages.
  test:flutter:
    run: melos exec --fail-fast -- flutter test
    description: Run Flutter tests in packages that support them.
  format:
    run: melos exec -- dart format .
    description: Format all packages.
  pana:
    run: melos exec -- dart pub global run pana --no-warning .
    description: Run pana analysis on all packages.
