name: tracekit_http
description: package:http client wrapper for TraceKit logging.
version: 0.3.0
homepage: https://github.com/tracekit/tracekit
repository: https://github.com/tracekit/tracekit/tree/main/packages/tracekit_http
issue_tracker: https://github.com/tracekit/tracekit/issues

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2
  tracekit:
    path: ../tracekit

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
