name: tracekit_dio
description: Dio HTTP interceptor for TraceKit with header/body redaction.
version: 0.3.0
homepage: https://github.com/vishalsharma7nov/tracekit
repository: https://github.com/vishalsharma7nov/tracekit/tree/master/packages/tracekit_dio
issue_tracker: https://github.com/vishalsharma7nov/tracekit/issues

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  tracekit:
    path: ../tracekit

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
