name: tracekit_bloc
description: BLoC observer for TraceKit logging.
version: 0.4.0
homepage: https://github.com/vishalsharma7nov/tracekit
repository: https://github.com/vishalsharma7nov/tracekit/tree/master/packages/tracekit_bloc
issue_tracker: https://github.com/vishalsharma7nov/tracekit/issues

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  tracekit:
    path: ../tracekit

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
